RETIRED_SOURCE_IDS = {
    "instagram-branded-content",
    "instagram-music-library",
}


OFFICIAL_SOURCES = [
    {
        "id": "instagram-best-practices-hub",
        "title": "Instagram Best Practices education hub",
        "url": "https://about.fb.com/news/2024/10/best-practices-education-hub-creators-instagram/",
        "source_type": "meta_official",
        "context": "organic",
        "tags": ["creation", "engagement", "reach", "monetization", "guidelines"],
        "refresh_days": 30,
    },
    {
        "id": "instagram-newsroom",
        "title": "Latest Instagram News",
        "url": "https://about.fb.com/news/category/technologies/instagram/",
        "source_type": "meta_official",
        "context": "product_updates",
        "tags": ["features", "creators", "instagram", "updates"],
        "refresh_days": 7,
    },
    {
        "id": "meta-recommendation-guidelines",
        "title": "Meta Recommendation Guidelines",
        "url": "https://about.fb.com/news/2020/08/recommendation-guidelines/",
        "source_type": "meta_official",
        "context": "policy",
        "tags": ["recommendations", "eligibility", "reach", "safety"],
        "refresh_days": 14,
    },
    {
        "id": "instagram-feed-ranking-system",
        "title": "Instagram Feed Ranking System Card",
        "url": "https://ai.meta.com/tools/system-cards/instagram-feed-ranking/",
        "source_type": "meta_official",
        "context": "organic",
        "tags": ["feed", "ranking", "likes", "saves", "comments"],
        "refresh_days": 30,
    },
    {
        "id": "instagram-explore-recommendations",
        "title": "Scaling Instagram Explore recommendations",
        "url": "https://engineering.fb.com/2023/08/09/ml-applications/scaling-instagram-explore-recommendations-system/",
        "source_type": "meta_official",
        "context": "organic",
        "tags": ["explore", "ranking", "recommendations", "discovery"],
        "refresh_days": 60,
    },
    {
        "id": "instagram-original-content-distribution",
        "title": "Helping creators find new audiences with original content",
        "url": "https://about.fb.com/ltam/news/2024/05/ayudando-a-los-creadores-a-encontrar-nuevas-audiencias/",
        "source_type": "meta_official",
        "context": "organic",
        "tags": ["original-content", "recommendations", "discovery", "distribution"],
        "refresh_days": 30,
    },
    {
        "id": "instagram-trial-reels",
        "title": "Trial Reels for testing content with non-followers",
        "url": "https://about.fb.com/news/2024/12/trial-reels-try-content-non-followers-first-see-what-perfoms-best/",
        "source_type": "meta_official",
        "context": "experimentation",
        "tags": ["trial-reels", "non-followers", "testing", "reach", "discovery"],
        "refresh_days": 30,
    },
    {
        "id": "instagram-reels-retention-insights",
        "title": "Reels replays and retention insights",
        "url": "https://about.fb.com/news/2023/11/new-ways-to-create-content-on-instagram/",
        "source_type": "meta_official",
        "context": "measurement",
        "tags": ["reels", "retention", "watch-time", "replays", "insights"],
        "refresh_days": 30,
    },
    {
        "id": "instagram-community-prompts-insights",
        "title": "Community replies, prompts and insights",
        "url": "https://about.fb.com/news/2024/12/get-closer-to-your-community-with-replies-prompts-and-insights/",
        "source_type": "meta_official",
        "context": "community",
        "tags": ["community", "replies", "prompts", "insights", "engagement"],
        "refresh_days": 30,
    },
    {
        "id": "meta-reels-creative-guidance",
        "title": "Meta creative guidance for Reels ads",
        "url": "https://www.facebook.com/business/ads/facebook-instagram-reels-ads",
        "source_type": "meta_official",
        "context": "paid",
        "tags": ["reels", "vertical-video", "safe-zone", "audio", "ads"],
        "refresh_days": 30,
    },
]
