OFFICIAL_SOURCES = [
    {
        "id": "instagram-best-practices-hub",
        "title": "Instagram Best Practices education hub",
        "url": "https://about.fb.com/news/2024/10/best-practices-education-hub-creators-instagram/",
        "source_type": "meta_official",
        "context": "organic",
        "tags": ["creation", "engagement", "reach", "monetization", "guidelines"],
        "refresh_days": 30,
    },
    {
        "id": "instagram-newsroom",
        "title": "Latest Instagram News",
        "url": "https://about.fb.com/news/category/technologies/instagram/",
        "source_type": "meta_official",
        "context": "product_updates",
        "tags": ["features", "creators", "instagram", "updates"],
        "refresh_days": 7,
    },
    {
        "id": "meta-recommendation-guidelines",
        "title": "Meta Recommendation Guidelines",
        "url": "https://about.fb.com/news/2020/08/recommendation-guidelines/",
        "source_type": "meta_official",
        "context": "policy",
        "tags": ["recommendations", "eligibility", "reach", "safety"],
        "refresh_days": 14,
    },
    {
        "id": "instagram-feed-ranking-system",
        "title": "Instagram Feed Ranking System Card",
        "url": "https://ai.meta.com/tools/system-cards/instagram-feed-ranking/",
        "source_type": "meta_official",
        "context": "organic",
        "tags": ["feed", "ranking", "likes", "saves", "comments"],
        "refresh_days": 30,
    },
    {
        "id": "instagram-explore-recommendations",
        "title": "Scaling Instagram Explore recommendations",
        "url": "https://engineering.fb.com/2023/08/09/ml-applications/scaling-instagram-explore-recommendations-system/",
        "source_type": "meta_official",
        "context": "organic",
        "tags": ["explore", "ranking", "recommendations", "discovery"],
        "refresh_days": 60,
    },
    {
        "id": "instagram-branded-content",
        "title": "What Instagram considers branded content",
        "url": "https://www.facebook.com/help/instagram/616901995832907",
        "source_type": "meta_official",
        "context": "policy",
        "tags": ["branded-content", "paid-partnership", "affiliate", "disclosure"],
        "refresh_days": 30,
    },
    {
        "id": "instagram-music-library",
        "title": "Access to the licensed music library on Instagram",
        "url": "https://www.facebook.com/help/instagram/402084904469945",
        "source_type": "meta_official",
        "context": "policy",
        "tags": ["music", "copyright", "reels", "commercial-use"],
        "refresh_days": 30,
    },
    {
        "id": "meta-reels-creative-guidance",
        "title": "Meta creative guidance for Reels ads",
        "url": "https://www.facebook.com/business/ads/facebook-instagram-reels-ads",
        "source_type": "meta_official",
        "context": "paid",
        "tags": ["reels", "vertical-video", "safe-zone", "audio", "ads"],
        "refresh_days": 30,
    },
]
